name: Build
on:
  push:
    branches:
      - main

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ['amd64']
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Configure project
        run: cmake --preset "win32-release-${{ matrix.arch }}"
      - name: Run appversion.sh
        run: regamedll/version/appversion.sh "${{ github.workspace }}/3rdparty/ReGameDLL_CS"
        shell: bash
        working-directory: 3rdparty/ReGameDLL_CS
      - name: Build
        run: cmake --build .
        working-directory: build
      - name: Generate extras.pk3
        run: Compress-Archive -Path 3rdparty/cs16client-extras/* -Destination build/extras.pk3 -CompressionLevel NoCompression
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: win32-${{ matrix.arch }}
          path: |
            build/3rdparty/ReGameDLL_CS/regamedll/mp.dll
            build/3rdparty/ReGameDLL_CS/regamedll/mp_amd64.dll
            build/3rdparty/mainui_cpp/menu.dll
            build/3rdparty/mainui_cpp/menu_amd64.dll
            build/cl_dll/client.dll
            build/cl_dll/client_amd64.dll
            build/extras.pk3
